# Generated by Django 4.2.4 on 2023-08-30 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi_name', models.CharField(max_length=33)),
                ('encryption', models.CharField(max_length=5)),
                ('password', models.CharField(max_length=33)),
                ('begin', models.DateTimeField(default=datetime.datetime(2023, 8, 30, 21, 25, 32, 390116))),
            ],
        ),
    ]
