# Generated by Django 4.2.4 on 2023-08-30 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrCodeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi_name', models.CharField(max_length=33)),
                ('encryption', models.CharField(choices=[('WPA', 'WPA'), ('WEP', 'WEP')], default='WPA', max_length=4)),
                ('password', models.CharField(max_length=33)),
                ('begin', models.DateTimeField(default=datetime.datetime(2023, 8, 30, 23, 49, 34, 991806))),
            ],
        ),
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
